import tkinter as pk
import tkinter.messagebox
from tkinter import *
from DCM.functions import *

row_DDD = []


def DDD_window():
    root_DDD = pk.Tk()
    root_DDD.title('DDD')
    root_DDD.geometry('380x680')

    with open("user.txt", 'r') as s_file:
        content = s_file.read()
        print(content)
    s_file.close()

    with open('{}.csv'.format(content), 'r+') as user_file:
        lines1 = user_file.readlines()
        user_file.truncate()
    user_file.close()

    for line1 in lines1:
        row_DDD.append(line1.split(','))
        while ['"\n'] in row_DDD:
            row_DDD.remove(['"\n'])
    for element in row_DDD:
        if '\n' in element:
            element.pop()

    Label(root_DDD, text='Lower Rate Limit:').grid(row=0, column=0)
    Label(root_DDD, text='Upper Rate Limit:').grid(row=1, column=0)
    Label(root_DDD, text='Fixed AV Delay:').grid(row=2, column=0)
    Label(root_DDD, text='Dynamic AV Delay:').grid(row=3, column=0)
    Label(root_DDD, text='Sensed AV Delay Offset:').grid(row=4, column=0)
    Label(root_DDD, text='Atrial Amplitude:').grid(row=5, column=0)
    Label(root_DDD, text='Ventricular Amplitude:').grid(row=6, column=0)
    Label(root_DDD, text='Atrial Pulse Width:').grid(row=7, column=0)
    Label(root_DDD, text='Ventricular Pulse Width:').grid(row=8, column=0)
    Label(root_DDD, text='Atrial Sensitivity:').grid(row=9, column=0)
    Label(root_DDD, text='Ventricular Sensitivity:').grid(row=10, column=0)
    Label(root_DDD, text='VRP:').grid(row=11, column=0)
    Label(root_DDD, text='ARP:').grid(row=12, column=0)
    Label(root_DDD, text='PVARP:').grid(row=13, column=0)
    Label(root_DDD, text='PVARP Extension:').grid(row=14, column=0)
    Label(root_DDD, text='Hysteresis(-1 as "off"):').grid(row=15, column=0)
    Label(root_DDD, text='Rate Smoothing(-1 as "off"):').grid(row=16, column=0)
    Label(root_DDD, text='ATR Duration:').grid(row=17, column=0)
    Label(root_DDD, text='ATR Fallback Mode:').grid(row=18, column=0)
    Label(root_DDD, text='ATR Fallback Time:').grid(row=19, column=0)

    v1 = pk.StringVar()
    v1.set(row_DDD[6][1])
    v2 = pk.StringVar()
    v2.set(row_DDD[6][2])
    v3 = pk.StringVar()
    v3.set(row_DDD[6][4])
    v4 = pk.StringVar()
    v4.set(row_DDD[6][5])
    v5 = pk.StringVar()
    v5.set(row_DDD[6][6])
    v6 = pk.StringVar()
    v6.set(row_DDD[6][7])
    v7 = pk.StringVar()
    v7.set(row_DDD[6][8])
    v8 = pk.StringVar()
    v8.set(row_DDD[6][9])
    v9 = pk.StringVar()
    v9.set(row_DDD[6][10])
    v10 = pk.StringVar()
    v10.set(row_DDD[6][11])
    v11 = pk.StringVar()
    v11.set(row_DDD[6][12])
    v12 = pk.StringVar()
    v12.set(row_DDD[6][13])
    v13 = pk.StringVar()
    v13.set(row_DDD[6][14])
    v14 = pk.StringVar()
    v14.set(row_DDD[6][15])
    v15 = pk.StringVar()
    v15.set(row_DDD[6][16])
    v16 = pk.StringVar()
    v16.set(row_DDD[6][17])
    v17 = pk.StringVar()
    v17.set(row_DDD[6][18])
    v18 = pk.StringVar()
    v18.set(row_DDD[6][19])
    v19 = pk.StringVar()
    v19.set(row_DDD[6][20])
    v20 = pk.StringVar()
    v20.set(row_DDD[6][21])


    e1 = Entry(root_DDD, textvariable=v1)
    e2 = Entry(root_DDD, textvariable=v2)
    e3 = Entry(root_DDD, textvariable=v3)
    e4 = Entry(root_DDD, textvariable=v4)
    e5 = Entry(root_DDD, textvariable=v5)
    e6 = Entry(root_DDD, textvariable=v6)
    e7 = Entry(root_DDD, textvariable=v7)
    e8 = Entry(root_DDD, textvariable=v8)
    e9 = Entry(root_DDD, textvariable=v9)
    e10 = Entry(root_DDD, textvariable=v10)
    e11 = Entry(root_DDD, textvariable=v11)
    e12 = Entry(root_DDD, textvariable=v12)
    e13 = Entry(root_DDD, textvariable=v13)
    e14 = Entry(root_DDD, textvariable=v14)
    e15 = Entry(root_DDD, textvariable=v15)
    e16 = Entry(root_DDD, textvariable=v16)
    e17 = Entry(root_DDD, textvariable=v17)
    e18 = Entry(root_DDD, textvariable=v18)
    e19 = Entry(root_DDD, textvariable=v19)
    e20 = Entry(root_DDD, textvariable=v20)


    e1.grid(row=0, column=1, padx=10, pady=5)
    e2.grid(row=1, column=1, padx=10, pady=5)
    e3.grid(row=2, column=1, padx=10, pady=5)
    e4.grid(row=3, column=1, padx=10, pady=5)
    e5.grid(row=4, column=1, padx=10, pady=5)
    e6.grid(row=5, column=1, padx=10, pady=5)
    e7.grid(row=6, column=1, padx=10, pady=5)
    e8.grid(row=7, column=1, padx=10, pady=5)
    e9.grid(row=8, column=1, padx=10, pady=5)
    e10.grid(row=9, column=1, padx=10, pady=5)
    e11.grid(row=10, column=1, padx=10, pady=5)
    e12.grid(row=11, column=1, padx=10, pady=5)
    e13.grid(row=12, column=1, padx=10, pady=5)
    e14.grid(row=13, column=1, padx=10, pady=5)
    e15.grid(row=14, column=1, padx=10, pady=5)
    e16.grid(row=15, column=1, padx=10, pady=5)
    e17.grid(row=16, column=1, padx=10, pady=5)
    e18.grid(row=17, column=1, padx=10, pady=5)
    e19.grid(row=18, column=1, padx=10, pady=5)
    e20.grid(row=19, column=1, padx=10, pady=5)

    # Button(root_DDD, text='Save', width=5, command=show_DDD_ASorVS()).place(x=50, y=290)
    Button(root_DDD, text='Fire', width=5, command=root_DDD.destroy).place(x=100, y=630)
    Button(root_DDD, text='Cancel', width=5, command=root_DDD.destroy).place(x=220, y=630)

    mainloop()